### ISSUE TITLE
Missing license content

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-recompress#13]
This source service is labeled as `GPL-2.0+` in the packaging, but there's no license file for the GPLv2. Can this be fixed, please?

This is necessary for me to package this source service in Fedora.

**Comment by seife** [comment]
License is stated in https://github.com/openSUSE/obs-service-recompress/blob/master/recompress#L7

**Comment by Conan-Kudo** [comment]
Yeah, I knew about the header in this one, but the GPLv2 requires a copy of the terms shipped with it, per  clause 1 of the GPLv2.

**Comment by adrianschroeter** [comment]
added now
